# Generated by Django 5.0 on 2023-12-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Product',
        ),
    ]
